import { NAME } from './constants';

export const FETCH_USERS_REQUEST = `${NAME}/FETCH_USERS_REQUEST`;
export const FETCH_USERS_SUCCESS = `${NAME}/FETCH_USERS_SUCCESS`;
export const FETCH_USERS_FAILURE = `${NAME}/FETCH_USERS_FAILURE`;
