import { NAME } from './constants';

export const FETCH_PLAYLISTS_REQUEST = `${NAME}/FETCH_PLAYLISTS_REQUEST`;
export const FETCH_PLAYLISTS_SUCCESS = `${NAME}/FETCH_PLAYLISTS_SUCCESS`;
export const FETCH_PLAYLISTS_FAILURE = `${NAME}/FETCH_PLAYLISTS_FAILURE`;
